# Generated by Django 3.0.5 on 2020-05-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidcasesmodel',
            name='cityimageurl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
